###########################################################
### Welcome to Beautiful Jekyll!
###########################################################

############################
# --- Required options --- #
############################

title: 叁的技术博客
author: 叁

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  博客: "/"
  About: "about"

###########################
# --- General options --- #
###########################

url: "https://AneSan333.github.io"
baseurl: ""

share-links-active:
  twitter: false
  facebook: false
  linkedin: false
  vk: false
  reddit: false

url-pretty: "AneSan333.github.io"
title-on-all-pages: true
excerpt_length: 50
feed_show_excerpt: false
feed_show_tags: false
post_search: false
edit_page_button: false
navbar-var-length: false
remove-ads: true

######################################
# --- Colours / background image --- #
######################################

page-col: "#fffaf0"
text-col: "#3a3a3a"
link-col: "#0a0a0a"
hover-col: "#1f1f1f"
navbar-col: "#fffaf0"
navbar-text-col: "#0a0a0a"
navbar-border-col: "#e5e5e5"
footer-col: "#faf5e8"
footer-text-col: "#3a3a3a"
footer-link-col: "#3a3a3a"
footer-hover-col: "#0a0a0a"

mobile-theme-col: "#fffaf0"

site-css:
  - "/assets/css/custom-styles.css"

################
# --- Misc --- #
################

date_format: "%B %-d, %Y"
excerpt_separator: "<!--more-->"

#################################################################################
# --- You don't need to touch anything below here (but you can if you want) --- #
#################################################################################

remote_theme: daattali/beautiful-jekyll@6.0.1

timezone: "Asia/Shanghai"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      social-share: false
  -
    scope:
      path: ""
    values:
      layout: "page"

exclude:
  - CHANGELOG.md
  - CNAME
  - DESIGN.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/
  - templates/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
